#!/usr/bin/env python3
"""
Generate src/generated/emot3.rc and src/generated/ResourcesGenerated.cpp
from the contents of resources/. Wired as a pre-build event in
src/emot3.vcxproj so dropping a new PNG into resources/emotes_official/
etc. gets picked up on the next compile without hand-editing anything.

Layout (relative to project root):
    resources/emotes_official/*.png   -> bundled official artwork
    resources/emotes_ai/*.png         -> bundled AI artwork (opt-in)
    resources/ui/*.png                -> bundled UI artwork
    resources/i18n/*.json             -> bundled UI translation tables
    resources/emote_data/*.json       -> bundled emote-localization table
    resources/presets/*.json          -> bundled default Quickbar presets
    resources/me_mote_data/*.json     -> bundled /me-mote seed table
    resources/me_motes_ai/*.png       -> bundled /me-mote AI artwork (opt-in).
                                         PNG stems MUST be valid normalized
                                         /me-mote ids ([a-z0-9_]) — the AI
                                         fallback tier matches on the user's
                                         m.Id via LookupBundledResource, and
                                         a mis-named drop-in (e.g. "Clap.png"
                                         or "ready-check.png") silently never
                                         resolves. See NormalizeMeMoteId.

Output:
    src/generated/emot3.rc               -> RCDATA entries for the resource
                                            compiler. Paths are written
                                            relative to the .rc's directory
                                            (src/generated/), which rc.exe
                                            resolves correctly under MSBuild.
    src/generated/ResourcesGenerated.cpp -> manifest arrays consumed by
                                            Resources.cpp via the declarations
                                            in Resources.h.

Both outputs live in src/generated/ to keep auto-generated files clearly
separated from the hand-written modules in src/core/, src/data/, etc.

Resource IDs are assigned deterministically (sorted alphabetically per
bucket, fixed base offset) so rebuilds produce stable identifiers even
when new PNGs are added.

  Official emote icons: 1000-1999
  AI emote icons:       2000-2999
  UI icons:             3000-3999
  UI translations:      4000-4999  (resources/i18n/*.json)
  Emote-locale data:    5000-5999  (resources/emote_data/*.json)
  Default presets:      6000-6999  (resources/presets/*.json)
  /me-mote seed data:   7000-7999  (resources/me_mote_data/*.json)
  /me-mote AI icons:    8000-8999  (resources/me_motes_ai/*.png; opt-in)

Each bucket has 1000 slots, which is plenty: GW2 currently ships ~67
emote commands. If we ever blow through a bucket the script will refuse
to generate rather than silently collide with the next one's range.

PNG buckets emit a `BundledIcon` manifest (icon stem -> resource id);
the JSON data buckets emit a `BundledData` manifest (file stem ->
resource id), looked up by name at runtime (see Resources.cpp). Both
struct shapes are identical; the distinct type names keep call sites
self-documenting.
"""

import glob
import os
import sys

SCRIPT_DIR    = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR   = os.path.dirname(SCRIPT_DIR)
RESOURCES_DIR = os.path.join(PROJECT_DIR, "resources")
SRC_DIR       = os.path.join(PROJECT_DIR, "src")
GEN_DIR       = os.path.join(SRC_DIR, "generated")
RC_PATH       = os.path.join(GEN_DIR, "emot3.rc")
GEN_CPP_PATH  = os.path.join(GEN_DIR, "ResourcesGenerated.cpp")

# (folder under resources/, base resource ID, C++ array name, file
#  extension, C++ struct type). PNG buckets use BundledIcon; JSON data
#  buckets use BundledData (identical layout, clearer call sites).
BUCKETS = [
    ("emotes_official", 1000, "kOfficialIcons", "png",  "BundledIcon"),
    ("emotes_ai",       2000, "kAIIcons",       "png",  "BundledIcon"),
    ("ui",              3000, "kUiIcons",       "png",  "BundledIcon"),
    ("i18n",            4000, "kI18nFiles",     "json", "BundledData"),
    ("emote_data",      5000, "kEmoteData",     "json", "BundledData"),
    ("presets",         6000, "kPresets",       "json", "BundledData"),
    ("me_mote_data",    7000, "kMeMoteData",    "json", "BundledData"),
    ("me_motes_ai",     8000, "kMeMoteAIIcons", "png",  "BundledIcon"),
]
BUCKET_CAPACITY = 1000


def collect(folder, ext):
    """Return [(stem_lowercase, abs_path), ...] sorted alphabetically."""
    pattern = os.path.join(RESOURCES_DIR, folder, "*." + ext)
    files   = sorted(glob.glob(pattern))
    out     = []
    for f in files:
        name = os.path.basename(f)
        stem = os.path.splitext(name)[0].lower()
        out.append((stem, f))
    return out


def write_rc(buckets):
    rc_dir = os.path.dirname(RC_PATH)
    lines  = [
        "// Generated by tools/gen_rc.py. DO NOT EDIT BY HAND.",
        "// Source of truth: resources/*.png filenames.",
        "",
    ]
    for folder, base_id, _, ext, _struct in buckets:
        files = collect(folder, ext)
        if not files:
            lines.append(f"// (no {folder} bundled)")
            lines.append("")
            continue
        if len(files) > BUCKET_CAPACITY:
            raise RuntimeError(
                f"{folder} has {len(files)} entries, exceeds bucket capacity "
                f"{BUCKET_CAPACITY}. Bump the base ID spacing in BUCKETS.")
        lines.append(f"// === {folder} (base ID {base_id}) ===")
        for i, (stem, path) in enumerate(files):
            # Resource compiler under MSBuild runs from the vcxproj's dir
            # (src/), so paths in the .rc are interpreted from there.
            rel = os.path.relpath(path, rc_dir).replace("\\", "/")
            lines.append(f"{base_id + i} RCDATA \"{rel}\"")
        lines.append("")
    with open(RC_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {RC_PATH}")


def write_cpp(buckets):
    lines = [
        "// Generated by tools/gen_rc.py. DO NOT EDIT BY HAND.",
        "// Source of truth: resources/*.png filenames.",
        "#include \"Resources.h\"",
        "",
    ]
    for folder, base_id, array_name, ext, struct_type in buckets:
        files = collect(folder, ext)
        lines.append(f"const {struct_type} {array_name}[] = {{")
        for i, (stem, _) in enumerate(files):
            lines.append(f"    {{ \"{stem}\", {base_id + i} }},")
        if not files:
            # MSVC disallows zero-sized arrays. Emit a null sentinel so the
            # array has at least one element; the explicit count below stays
            # at 0, so the lookup never dereferences it.
            lines.append("    { nullptr, 0 },")
        lines.append("};")
        lines.append(f"const int {array_name}Count = {len(files)};")
        lines.append("")
    with open(GEN_CPP_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {GEN_CPP_PATH}")


def main():
    if not os.path.isdir(RESOURCES_DIR):
        print(f"resources/ missing at {RESOURCES_DIR}", file=sys.stderr)
        return 1
    if not os.path.isdir(SRC_DIR):
        print(f"src/ missing at {SRC_DIR}", file=sys.stderr)
        return 1
    # Create the generated/ subdir if needed - happens on first run
    # or after the directory is wiped for a clean build.
    os.makedirs(GEN_DIR, exist_ok=True)
    write_rc(BUCKETS)
    write_cpp(BUCKETS)
    return 0


if __name__ == "__main__":
    sys.exit(main())
